;;; cheatsheet-entries.el --- Cheatsheet data -*- lexical-binding: t -*-
;;
;; Registers all entries via my/cheatsheet-add.
;; Keybindings and package names are auto-detected at render time.
;; Load after cheatsheet.el.

;;; Code:

;;;; ---- Buffers & Windows ----

(my/cheatsheet-add "Buffers & Windows" 'consult-buffer "Switch buffer with preview and virtual buffers")
(my/cheatsheet-add "Buffers & Windows" 'consult-buffer-other-window "Switch buffer in other window")
(my/cheatsheet-add "Buffers & Windows" 'consult-project-buffer "Switch buffer scoped to current project")
(my/cheatsheet-add "Buffers & Windows" 'ibuffer "List buffers for bulk operations")
(my/cheatsheet-add "Buffers & Windows" 'ace-window "Select, swap, or delete window by label")
(my/cheatsheet-add "Buffers & Windows" 'ace-select-window "Select a window by label")
(my/cheatsheet-add "Buffers & Windows" 'ace-swap-window "Swap current window with selected one")
(my/cheatsheet-add "Buffers & Windows" 'ace-delete-window "Delete a window by label")
(my/cheatsheet-add "Buffers & Windows" 'ace-delete-other-windows "Delete all windows except selected one")
(my/cheatsheet-add "Buffers & Windows" 'aw-flip-window "Switch to the previous window")
(my/cheatsheet-add "Buffers & Windows" 'winner-undo "Restore previous window configuration")
(my/cheatsheet-add "Buffers & Windows" 'winner-redo "Redo window configuration change")
(my/cheatsheet-add "Buffers & Windows" 'popper-toggle "Toggle visibility of last popup window")
(my/cheatsheet-add "Buffers & Windows" 'popper-cycle "Cycle through popup windows")
(my/cheatsheet-add "Buffers & Windows" 'popper-cycle-backwards "Cycle popup windows in reverse")
(my/cheatsheet-add "Buffers & Windows" 'popper-toggle-type "Convert popup to regular window or vice versa")
(my/cheatsheet-add "Buffers & Windows" 'popper-kill-latest-popup "Kill latest popup buffer and window")
(my/cheatsheet-add "Buffers & Windows" 'crux-transpose-windows "Swap buffers of two windows")
(my/cheatsheet-add "Buffers & Windows" 'crux-switch-to-previous-buffer "Toggle between two most recent buffers")
(my/cheatsheet-add "Buffers & Windows" 'crux-kill-other-buffers "Kill all buffers except current")

;;;; ---- Minibuffer Completion ----

(my/cheatsheet-add "Minibuffer Completion" 'vertico-directory-enter "Enter directory or exit with candidate")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-directory-delete-char "Delete char or go up one directory")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-directory-delete-word "Delete word or directory component")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-repeat "Repeat last vertico completion session")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-repeat-select "Select and repeat a past session")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-quick-insert "Insert candidate using quick keys")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-quick-exit "Exit with candidate using quick keys")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-multiform-buffer "Toggle buffer display in minibuffer")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-multiform-flat "Toggle flat display in minibuffer")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-multiform-grid "Toggle grid display in minibuffer")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-multiform-reverse "Toggle reverse display in minibuffer")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-exit-input "Exit with raw input, not selected candidate")
(my/cheatsheet-add "Minibuffer Completion" 'vertico-save "Save current candidate to kill ring")
(my/cheatsheet-add "Minibuffer Completion" 'marginalia-cycle "Cycle between annotation styles")

;;;; ---- Search & Filter ----

(my/cheatsheet-add "Search & Filter" 'isearch-forward "Incremental search forward")
(my/cheatsheet-add "Search & Filter" 'isearch-backward "Incremental search backward")
(my/cheatsheet-add "Search & Filter" 'consult-line "Search lines in current buffer")
(my/cheatsheet-add "Search & Filter" 'consult-line-multi "Search lines across multiple buffers")
(my/cheatsheet-add "Search & Filter" 'consult-ripgrep "Search file contents with ripgrep")
(my/cheatsheet-add "Search & Filter" 'consult-grep "Search file contents with grep")
(my/cheatsheet-add "Search & Filter" 'consult-git-grep "Search file contents with git grep")
(my/cheatsheet-add "Search & Filter" 'consult-fd "Find files by name with fd")
(my/cheatsheet-add "Search & Filter" 'consult-find "Find files by name with find")
(my/cheatsheet-add "Search & Filter" 'consult-keep-lines "Keep only lines matching pattern")
(my/cheatsheet-add "Search & Filter" 'consult-focus-lines "Show only matching lines via overlays")
(my/cheatsheet-add "Search & Filter" 'consult-isearch-history "Resume isearch via completion")

;;;; ---- Navigation ----

(my/cheatsheet-add "Navigation" 'avy-goto-char-timer "Jump to visible text by typing chars")
(my/cheatsheet-add "Navigation" 'avy-goto-word-1 "Jump to word starting with given char")
(my/cheatsheet-add "Navigation" 'avy-goto-line "Jump to a visible line")
(my/cheatsheet-add "Navigation" 'avy-goto-char-2 "Jump to visible two-char sequence")
(my/cheatsheet-add "Navigation" 'avy-goto-end-of-line "Jump to end of a visible line")
(my/cheatsheet-add "Navigation" 'avy-isearch "Jump to an isearch candidate via avy")
(my/cheatsheet-add "Navigation" 'avy-resume "Repeat the last avy command")
(my/cheatsheet-add "Navigation" 'avy-pop-mark "Jump back to last avy mark")
(my/cheatsheet-add "Navigation" 'avy-copy-line "Copy a visible line to current position")
(my/cheatsheet-add "Navigation" 'avy-copy-region "Copy region between two avy points")
(my/cheatsheet-add "Navigation" 'avy-move-line "Move a visible line to current position")
(my/cheatsheet-add "Navigation" 'avy-move-region "Move region between two avy points")
(my/cheatsheet-add "Navigation" 'avy-kill-whole-line "Kill a visible line via avy selection")
(my/cheatsheet-add "Navigation" 'avy-kill-region "Kill region between two avy points")
(my/cheatsheet-add "Navigation" 'consult-goto-line "Jump to line number with live preview")
(my/cheatsheet-add "Navigation" 'consult-imenu "Jump to imenu item with preview")
(my/cheatsheet-add "Navigation" 'consult-imenu-multi "Jump to imenu item across project buffers")
(my/cheatsheet-add "Navigation" 'consult-outline "Jump to outline heading with preview")
(my/cheatsheet-add "Navigation" 'consult-mark "Jump to marker in local mark ring")
(my/cheatsheet-add "Navigation" 'consult-global-mark "Jump to marker in global mark ring")
(my/cheatsheet-add "Navigation" 'consult-bookmark "Browse and jump to bookmarks")
(my/cheatsheet-add "Navigation" 'bookmark-set "Set bookmark at point")
(my/cheatsheet-add "Navigation" 'xref-find-definitions "Jump to definition of symbol at point")
(my/cheatsheet-add "Navigation" 'xref-go-back "Return to location before last jump")
(my/cheatsheet-add "Navigation" 'xref-find-references "Find all references to symbol at point")
(my/cheatsheet-add "Navigation" 'xref-find-apropos "Search symbols matching a pattern")

;;;; ---- Symbol Overlay ----

(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-put "Toggle highlight of symbol at point")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-jump-next "Jump to next occurrence of symbol")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-jump-prev "Jump to previous occurrence of symbol")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-jump-first "Jump to first occurrence of symbol")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-jump-last "Jump to last occurrence of symbol")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-rename "Rename symbol at all occurrences")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-query-replace "Query-replace symbol at point")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-remove-all "Remove all symbol highlights")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-switch-forward "Switch to next highlighted symbol")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-switch-backward "Switch to previous highlighted symbol")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-toggle-in-scope "Toggle scope: buffer vs defun")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-save-symbol "Copy symbol at point to kill ring")
(my/cheatsheet-add "Symbol Overlay" 'symbol-overlay-count "Show count of symbol at point")

;;;; ---- Actions (Embark) ----

(my/cheatsheet-add "Actions (Embark)" 'embark-act "Act on target at point or in minibuffer")
(my/cheatsheet-add "Actions (Embark)" 'embark-dwim "Run default action on target")
(my/cheatsheet-add "Actions (Embark)" 'embark-act-all "Act on all candidates at once")
(my/cheatsheet-add "Actions (Embark)" 'embark-select "Toggle selection for embark-act-all")
(my/cheatsheet-add "Actions (Embark)" 'embark-collect "Collect candidates into a buffer")
(my/cheatsheet-add "Actions (Embark)" 'embark-live "Live-updating collect buffer")
(my/cheatsheet-add "Actions (Embark)" 'embark-export "Export candidates to mode-specific buffer")
(my/cheatsheet-add "Actions (Embark)" 'embark-become "Switch current command to a different one")
(my/cheatsheet-add "Actions (Embark)" 'embark-bindings "Explore all current key bindings")
(my/cheatsheet-add "Actions (Embark)" 'embark-prefix-help-command "Show commands under current prefix key")
(my/cheatsheet-add "Actions (Embark)" 'embark-copy-as-kill "Save target string to kill ring")
(my/cheatsheet-add "Actions (Embark)" 'embark-open-externally "Open file or URL with system app")
(my/cheatsheet-add "Actions (Embark)" 'embark-dired-jump "Open dired at target file's directory")
(my/cheatsheet-add "Actions (Embark)" 'embark-find-definition "Jump to definition of elisp symbol")
(my/cheatsheet-add "Actions (Embark)" 'embark-toggle-highlight "Toggle highlight of symbol at point")
(my/cheatsheet-add "Actions (Embark)" 'embark-next-symbol "Jump to next occurrence of symbol")
(my/cheatsheet-add "Actions (Embark)" 'embark-previous-symbol "Jump to previous occurrence of symbol")
(my/cheatsheet-add "Actions (Embark)" 'embark-kill-ring-remove "Remove entry from kill ring")
(my/cheatsheet-add "Actions (Embark)" 'embark-history-remove "Remove entry from minibuffer history")
(my/cheatsheet-add "Actions (Embark)" 'embark-rename-buffer "Rename a buffer")

;;;; ---- In-Buffer Completion ----

(my/cheatsheet-add "In-Buffer Completion" 'corfu-complete "Complete or expand common prefix")
(my/cheatsheet-add "In-Buffer Completion" 'corfu-insert "Insert selected candidate and quit")
(my/cheatsheet-add "In-Buffer Completion" 'corfu-quit "Dismiss completion popup")
(my/cheatsheet-add "In-Buffer Completion" 'corfu-quick-complete "Complete candidate using quick keys")
(my/cheatsheet-add "In-Buffer Completion" 'corfu-quick-insert "Insert candidate using quick keys")
(my/cheatsheet-add "In-Buffer Completion" 'corfu-insert-separator "Insert orderless separator in corfu")
(my/cheatsheet-add "In-Buffer Completion" 'corfu-popupinfo-toggle "Toggle documentation popup")
(my/cheatsheet-add "In-Buffer Completion" 'corfu-popupinfo-scroll-up "Scroll documentation popup up")
(my/cheatsheet-add "In-Buffer Completion" 'corfu-popupinfo-scroll-down "Scroll documentation popup down")
(my/cheatsheet-add "In-Buffer Completion" 'cape-dabbrev "Complete word from open buffers")
(my/cheatsheet-add "In-Buffer Completion" 'cape-file "Complete file path at point")
(my/cheatsheet-add "In-Buffer Completion" 'cape-keyword "Complete language keyword")
(my/cheatsheet-add "In-Buffer Completion" 'cape-elisp-symbol "Complete elisp symbol at point")
(my/cheatsheet-add "In-Buffer Completion" 'cape-line "Complete entire line from buffer")
(my/cheatsheet-add "In-Buffer Completion" 'cape-dict "Complete word from dictionary")
(my/cheatsheet-add "In-Buffer Completion" 'cape-history "Complete from input history")
(my/cheatsheet-add "In-Buffer Completion" 'hippie-expand "Smart expansion: dabbrev, files, symbols")
(my/cheatsheet-add "In-Buffer Completion" 'consult-yank-pop "Select from kill ring with preview")

;;;; ---- Code Intelligence ----

(my/cheatsheet-add "Code Intelligence" 'eglot-ensure "Start LSP server for current buffer")
(my/cheatsheet-add "Code Intelligence" 'eglot-rename "Rename symbol across project via LSP")
(my/cheatsheet-add "Code Intelligence" 'eglot-code-actions "Show available code actions at point")
(my/cheatsheet-add "Code Intelligence" 'eglot-code-action-quickfix "Apply quickfix code action")
(my/cheatsheet-add "Code Intelligence" 'eglot-code-action-organize-imports "Organize imports via LSP")
(my/cheatsheet-add "Code Intelligence" 'eglot-format-buffer "Format entire buffer via LSP")
(my/cheatsheet-add "Code Intelligence" 'eglot-format "Format region or defun via LSP")
(my/cheatsheet-add "Code Intelligence" 'eglot-find-declaration "Jump to declaration via LSP")
(my/cheatsheet-add "Code Intelligence" 'eglot-find-implementation "Jump to implementation via LSP")
(my/cheatsheet-add "Code Intelligence" 'eglot-find-typeDefinition "Jump to type definition via LSP")
(my/cheatsheet-add "Code Intelligence" 'eglot-inlay-hints-mode "Toggle inlay type/parameter hints")
(my/cheatsheet-add "Code Intelligence" 'eglot-shutdown "Shut down LSP server for project")
(my/cheatsheet-add "Code Intelligence" 'eglot-reconnect "Restart the LSP server")
(my/cheatsheet-add "Code Intelligence" 'consult-eglot-symbols "Search workspace symbols via consult")
(my/cheatsheet-add "Code Intelligence" 'flymake-goto-next-error "Jump to next diagnostic")
(my/cheatsheet-add "Code Intelligence" 'flymake-goto-prev-error "Jump to previous diagnostic")
(my/cheatsheet-add "Code Intelligence" 'consult-flymake "Browse all diagnostics via consult")
(my/cheatsheet-add "Code Intelligence" 'flymake-show-buffer-diagnostics "List all diagnostics in buffer")
(my/cheatsheet-add "Code Intelligence" 'flymake-show-project-diagnostics "List diagnostics across entire project")

;;;; ---- Editing ----

(my/cheatsheet-add "Editing" 'crux-move-beginning-of-line "Toggle between indentation and column 0")
(my/cheatsheet-add "Editing" 'crux-smart-kill-line "Kill to EOL, then kill whole line on repeat")
(my/cheatsheet-add "Editing" 'crux-smart-open-line "Open line below with correct indentation")
(my/cheatsheet-add "Editing" 'crux-smart-open-line-above "Open line above with correct indentation")
(my/cheatsheet-add "Editing" 'crux-duplicate-current-line-or-region "Duplicate current line or region")
(my/cheatsheet-add "Editing" 'crux-duplicate-and-comment-current-line-or-region "Comment line then duplicate it")
(my/cheatsheet-add "Editing" 'crux-kill-whole-line "Kill entire line respecting indentation")
(my/cheatsheet-add "Editing" 'crux-kill-line-backwards "Kill from point to beginning of line")
(my/cheatsheet-add "Editing" 'crux-top-join-line "Join current line with line below")
(my/cheatsheet-add "Editing" 'crux-cleanup-buffer-or-region "Untabify, indent, and clean whitespace")
(my/cheatsheet-add "Editing" 'crux-indent-defun "Indent the current defun")
(my/cheatsheet-add "Editing" 'crux-eval-and-replace "Replace preceding sexp with its value")
(my/cheatsheet-add "Editing" 'crux-upcase-region "Upcase active region (safe)")
(my/cheatsheet-add "Editing" 'crux-downcase-region "Downcase active region (safe)")
(my/cheatsheet-add "Editing" 'crux-capitalize-region "Capitalize active region (safe)")
(my/cheatsheet-add "Editing" 'crux-insert-date "Insert timestamp at point")
(my/cheatsheet-add "Editing" 'crux-ispell-word-then-abbrev "Spell-correct word and save as abbrev")

;;;; ---- Grep & Replace ----

(my/cheatsheet-add "Grep & Replace" 'wgrep-change-to-wgrep-mode "Make grep results editable")
(my/cheatsheet-add "Grep & Replace" 'wgrep-finish-edit "Apply edits to original files")
(my/cheatsheet-add "Grep & Replace" 'wgrep-abort-changes "Discard all grep edits")
(my/cheatsheet-add "Grep & Replace" 'wgrep-save-all-buffers "Save all buffers changed by wgrep")
(my/cheatsheet-add "Grep & Replace" 'wgrep-remove-change "Remove edits in region")
(my/cheatsheet-add "Grep & Replace" 'wgrep-remove-all-change "Remove all pending edits")

;;;; ---- Git ----

(my/cheatsheet-add "Git" 'magit-status "Open git status buffer")
(my/cheatsheet-add "Git" 'magit-dispatch "Invoke a magit command from popup")
(my/cheatsheet-add "Git" 'magit-file-dispatch "Invoke magit command on current file")
(my/cheatsheet-add "Git" 'magit-log-current "Show log for current branch")
(my/cheatsheet-add "Git" 'magit-log-buffer-file "Show log for visited file")
(my/cheatsheet-add "Git" 'magit-log-trace-definition "Show log for definition at point")
(my/cheatsheet-add "Git" 'magit-log-all-branches "Show log for all branches")
(my/cheatsheet-add "Git" 'magit-diff-dwim "Show changes for thing at point")
(my/cheatsheet-add "Git" 'magit-diff-staged "Show diff of staged changes")
(my/cheatsheet-add "Git" 'magit-diff-unstaged "Show diff of unstaged changes")
(my/cheatsheet-add "Git" 'magit-show-commit "Show a commit's changes in a buffer")
(my/cheatsheet-add "Git" 'magit-diff-visit-file "Visit file at point from a diff")
(my/cheatsheet-add "Git" 'magit-checkout "Checkout a commit or branch")
(my/cheatsheet-add "Git" 'magit-branch-checkout "Checkout an existing or new branch")
(my/cheatsheet-add "Git" 'magit-branch-create "Create a new branch at a point")
(my/cheatsheet-add "Git" 'magit-branch-delete "Delete one or more branches")
(my/cheatsheet-add "Git" 'magit-branch-rename "Rename a branch")
(my/cheatsheet-add "Git" 'magit-branch-spinoff "Create branch from unpushed commits")
(my/cheatsheet-add "Git" 'magit-stash-both "Stash index and working tree changes")
(my/cheatsheet-add "Git" 'magit-stash-pop "Apply stash and remove from list")
(my/cheatsheet-add "Git" 'magit-stash-apply "Apply stash, keep in stash list")
(my/cheatsheet-add "Git" 'magit-stash-drop "Remove stash from list")
(my/cheatsheet-add "Git" 'magit-find-file "View file from a specific revision")
(my/cheatsheet-add "Git" 'magit-file-stage "Stage the current file")
(my/cheatsheet-add "Git" 'magit-file-unstage "Unstage the current file")
(my/cheatsheet-add "Git" 'magit-blob-previous "Visit previous revision of blob")
(my/cheatsheet-add "Git" 'magit-blob-next "Visit next revision of blob")
(my/cheatsheet-add "Git" 'diff-hl-next-hunk "Jump to next changed hunk in fringe")
(my/cheatsheet-add "Git" 'diff-hl-previous-hunk "Jump to previous changed hunk in fringe")
(my/cheatsheet-add "Git" 'diff-hl-revert-hunk "Revert the hunk at point")
(my/cheatsheet-add "Git" 'diff-hl-stage-current-hunk "Stage the hunk at point")
(my/cheatsheet-add "Git" 'diff-hl-stage-dwim "Stage current hunk or choose hunks")
(my/cheatsheet-add "Git" 'diff-hl-unstage-file "Unstage all changes in current file")
(my/cheatsheet-add "Git" 'diff-hl-diff-goto-hunk "Show VC diff and jump to hunk")
(my/cheatsheet-add "Git" 'diff-hl-mark-hunk "Mark the hunk at point")
(my/cheatsheet-add "Git" 'diff-hl-set-reference-rev "Set reference revision for diffs")

;;;; ---- Project ----

(my/cheatsheet-add "Project" 'project-find-file "Find file in current project")
(my/cheatsheet-add "Project" 'project-find-regexp "Grep across project files")
(my/cheatsheet-add "Project" 'project-find-dir "Find directory in project")
(my/cheatsheet-add "Project" 'project-dired "Open project root in dired")
(my/cheatsheet-add "Project" 'project-eshell "Open eshell in project root")
(my/cheatsheet-add "Project" 'project-switch-project "Switch to a different project")
(my/cheatsheet-add "Project" 'project-compile "Run compile command in project root")
(my/cheatsheet-add "Project" 'project-kill-buffers "Kill all buffers in current project")

;;;; ---- File Management ----

(my/cheatsheet-add "File Management" 'crux-rename-file-and-buffer "Rename current file and its buffer")
(my/cheatsheet-add "File Management" 'crux-delete-file-and-buffer "Delete file and kill its buffer")
(my/cheatsheet-add "File Management" 'crux-copy-file-preserve-attributes "Copy file preserving attributes")
(my/cheatsheet-add "File Management" 'crux-sudo-edit "Edit current file as root")
(my/cheatsheet-add "File Management" 'crux-reopen-as-root "Reopen file as root if unwritable")
(my/cheatsheet-add "File Management" 'crux-kill-buffer-truename "Copy file's absolute path to kill ring")
(my/cheatsheet-add "File Management" 'crux-find-user-init-file "Open user init file")
(my/cheatsheet-add "File Management" 'crux-find-shell-init-file "Open shell init file")
(my/cheatsheet-add "File Management" 'crux-recentf-find-file "Find recent file via completion")
(my/cheatsheet-add "File Management" 'consult-recent-file "Find recent file with preview")

;;;; ---- Dired ----

(my/cheatsheet-add "Dired" 'dired "Open directory in dired")
(my/cheatsheet-add "Dired" 'dired-find-file "Open file or enter directory")
(my/cheatsheet-add "Dired" 'dired-up-directory "Go to parent directory")
(my/cheatsheet-add "Dired" 'dired-do-copy "Copy marked files")
(my/cheatsheet-add "Dired" 'dired-do-rename "Move or rename marked files")
(my/cheatsheet-add "Dired" 'dired-do-delete "Delete marked files")
(my/cheatsheet-add "Dired" 'dired-mark "Mark file at point")
(my/cheatsheet-add "Dired" 'dired-unmark "Unmark file at point")
(my/cheatsheet-add "Dired" 'dired-toggle-marks "Toggle all marks")
(my/cheatsheet-add "Dired" 'dired-create-directory "Create new directory")
(my/cheatsheet-add "Dired" 'dired-do-shell-command "Run shell command on marked files")
(my/cheatsheet-add "Dired" 'wdired-change-to-wdired-mode "Edit filenames directly in buffer")

;;;; ---- Org Mode ----

(my/cheatsheet-add "Org Mode" 'org-agenda "Open agenda dispatcher")
(my/cheatsheet-add "Org Mode" 'org-capture "Capture new entry (todo, note, journal)")
(my/cheatsheet-add "Org Mode" 'org-store-link "Store link to current location")
(my/cheatsheet-add "Org Mode" 'org-insert-link "Insert or edit a link")
(my/cheatsheet-add "Org Mode" 'org-open-at-point "Open link at point")
(my/cheatsheet-add "Org Mode" 'org-refile "Move heading to another location")
(my/cheatsheet-add "Org Mode" 'org-todo "Cycle TODO state of heading")
(my/cheatsheet-add "Org Mode" 'org-schedule "Schedule heading for a date")
(my/cheatsheet-add "Org Mode" 'org-deadline "Set deadline for a heading")
(my/cheatsheet-add "Org Mode" 'org-set-tags-command "Set tags on current heading")
(my/cheatsheet-add "Org Mode" 'org-edit-special "Edit source block in dedicated buffer")
(my/cheatsheet-add "Org Mode" 'org-export-dispatch "Export to HTML, PDF, etc.")
(my/cheatsheet-add "Org Mode" 'org-archive-subtree "Archive completed subtree")
(my/cheatsheet-add "Org Mode" 'consult-org-heading "Jump to org heading with preview")
(my/cheatsheet-add "Org Mode" 'consult-org-agenda "Jump to agenda heading with preview")

;;;; ---- Markdown ----

(my/cheatsheet-add "Markdown" 'markdown-insert-bold "Toggle bold markup on region or word")
(my/cheatsheet-add "Markdown" 'markdown-insert-italic "Toggle italic markup on region or word")
(my/cheatsheet-add "Markdown" 'markdown-insert-code "Toggle inline code on region or word")
(my/cheatsheet-add "Markdown" 'markdown-insert-strike-through "Toggle strikethrough on region or word")
(my/cheatsheet-add "Markdown" 'markdown-insert-link "Insert or update a link")
(my/cheatsheet-add "Markdown" 'markdown-insert-image "Insert or update an image")
(my/cheatsheet-add "Markdown" 'markdown-insert-gfm-code-block "Insert fenced code block with language")
(my/cheatsheet-add "Markdown" 'markdown-insert-blockquote "Insert blockquote or blockquote region")
(my/cheatsheet-add "Markdown" 'markdown-insert-footnote "Insert footnote marker and definition")
(my/cheatsheet-add "Markdown" 'markdown-insert-header-dwim "Insert or replace header by context")
(my/cheatsheet-add "Markdown" 'markdown-insert-header-atx-1 "Insert level-1 heading")
(my/cheatsheet-add "Markdown" 'markdown-insert-header-atx-2 "Insert level-2 heading")
(my/cheatsheet-add "Markdown" 'markdown-insert-header-atx-3 "Insert level-3 heading")
(my/cheatsheet-add "Markdown" 'markdown-insert-list-item "Insert new list item")
(my/cheatsheet-add "Markdown" 'markdown-insert-gfm-checkbox "Add GFM task checkbox at point")
(my/cheatsheet-add "Markdown" 'markdown-insert-table "Insert an empty pipe table")
(my/cheatsheet-add "Markdown" 'markdown-insert-hr "Insert horizontal rule")
(my/cheatsheet-add "Markdown" 'markdown-do "Context-aware action at point")
(my/cheatsheet-add "Markdown" 'markdown-follow-thing-at-point "Follow link or reference at point")
(my/cheatsheet-add "Markdown" 'markdown-edit-code-block "Edit code block in indirect buffer")
(my/cheatsheet-add "Markdown" 'markdown-promote "Promote heading or list item")
(my/cheatsheet-add "Markdown" 'markdown-demote "Demote heading or list item")
(my/cheatsheet-add "Markdown" 'markdown-move-up "Move heading or list item up")
(my/cheatsheet-add "Markdown" 'markdown-move-down "Move heading or list item down")
(my/cheatsheet-add "Markdown" 'markdown-cycle "Visibility cycling for headings")
(my/cheatsheet-add "Markdown" 'markdown-shifttab "Global visibility cycling")
(my/cheatsheet-add "Markdown" 'markdown-toggle-markup-hiding "Toggle hiding of markup chars")
(my/cheatsheet-add "Markdown" 'markdown-toggle-url-hiding "Toggle hiding of URLs in links")
(my/cheatsheet-add "Markdown" 'markdown-toggle-inline-images "Toggle display of inline images")
(my/cheatsheet-add "Markdown" 'markdown-toggle-gfm-checkbox "Toggle GFM task checkbox state")
(my/cheatsheet-add "Markdown" 'markdown-table-align "Align table at point")
(my/cheatsheet-add "Markdown" 'markdown-table-insert-row "Insert new table row")
(my/cheatsheet-add "Markdown" 'markdown-table-insert-column "Insert new table column")
(my/cheatsheet-add "Markdown" 'markdown-table-delete-row "Delete table row at point")
(my/cheatsheet-add "Markdown" 'markdown-table-delete-column "Delete table column at point")
(my/cheatsheet-add "Markdown" 'markdown-table-transpose "Transpose table rows and columns")
(my/cheatsheet-add "Markdown" 'markdown-preview "Render markdown and open in browser")
(my/cheatsheet-add "Markdown" 'markdown-export "Export markdown to HTML file")
(my/cheatsheet-add "Markdown" 'markdown-live-preview-mode "Toggle live preview in eww")
(my/cheatsheet-add "Markdown" 'markdown-check-refs "Show undefined references")
(my/cheatsheet-add "Markdown" 'markdown-cleanup-list-numbers "Renumber ordered list items")

;;;; ---- Shell ----

(my/cheatsheet-add "Shell" 'eshell "Open eshell")
(my/cheatsheet-add "Shell" 'project-eshell "Open eshell in project root")
(my/cheatsheet-add "Shell" 'consult-history "Fuzzy search through shell history")
(my/cheatsheet-add "Shell" 'crux-visit-term-buffer "Create or visit a terminal buffer")
(my/cheatsheet-add "Shell" 'crux-visit-shell-buffer "Create or visit a shell buffer")

;;;; ---- Spell Checking ----

(my/cheatsheet-add "Spell Checking" 'flyspell-mode "Toggle on-the-fly spell checking")
(my/cheatsheet-add "Spell Checking" 'flyspell-correct-word-before-point "Correct misspelled word before point")
(my/cheatsheet-add "Spell Checking" 'flyspell-auto-correct-word "Auto-correct word at point")
(my/cheatsheet-add "Spell Checking" 'flyspell-goto-next-error "Jump to next misspelling")
(my/cheatsheet-add "Spell Checking" 'ispell-word "Check or correct word at point")
(my/cheatsheet-add "Spell Checking" 'ispell-buffer "Check entire buffer for misspellings")
(my/cheatsheet-add "Spell Checking" 'ispell-region "Check selected region for misspellings")
(my/cheatsheet-add "Spell Checking" 'ispell-change-dictionary "Switch spelling dictionary")

;;;; ---- Casual Menus ----

(my/cheatsheet-add "Casual Menus" 'casual-calc-tmenu "Transient menu for Calc")
(my/cheatsheet-add "Casual Menus" 'casual-dired-tmenu "Transient menu for Dired")
(my/cheatsheet-add "Casual Menus" 'casual-ibuffer-tmenu "Transient menu for IBuffer")
(my/cheatsheet-add "Casual Menus" 'casual-ibuffer-filter-tmenu "Transient menu for IBuffer filters")
(my/cheatsheet-add "Casual Menus" 'casual-ibuffer-sortby-tmenu "Transient menu for IBuffer sorting")
(my/cheatsheet-add "Casual Menus" 'casual-info-tmenu "Transient menu for Info reader")
(my/cheatsheet-add "Casual Menus" 'casual-re-builder-tmenu "Transient menu for RE-Builder")
(my/cheatsheet-add "Casual Menus" 'casual-bookmarks-tmenu "Transient menu for Bookmarks")
(my/cheatsheet-add "Casual Menus" 'casual-agenda-tmenu "Transient menu for Org Agenda")
(my/cheatsheet-add "Casual Menus" 'casual-avy-tmenu "Transient menu for Avy navigation")
(my/cheatsheet-add "Casual Menus" 'casual-symbol-overlay-tmenu "Transient menu for Symbol Overlay")
(my/cheatsheet-add "Casual Menus" 'casual-editkit-main-tmenu "Transient menu for general editing")
(my/cheatsheet-add "Casual Menus" 'casual-compile-tmenu "Transient menu for Compilation")
(my/cheatsheet-add "Casual Menus" 'casual-isearch-tmenu "Transient menu for I-Search")
(my/cheatsheet-add "Casual Menus" 'casual-org-tmenu "Transient menu for Org mode")
(my/cheatsheet-add "Casual Menus" 'casual-eshell-tmenu "Transient menu for Eshell")
(my/cheatsheet-add "Casual Menus" 'casual-ediff-tmenu "Transient menu for Ediff sessions")
(my/cheatsheet-add "Casual Menus" 'casual-elisp-tmenu "Transient menu for Emacs Lisp")
(my/cheatsheet-add "Casual Menus" 'casual-help-tmenu "Transient menu for Help mode")
(my/cheatsheet-add "Casual Menus" 'casual-man-tmenu "Transient menu for Man pages")
(my/cheatsheet-add "Casual Menus" 'casual-ispell-tmenu "Transient menu for spell checking")
(my/cheatsheet-add "Casual Menus" 'casual-image-tmenu "Transient menu for Image mode")
(my/cheatsheet-add "Casual Menus" 'casual-calendar-tmenu "Transient menu for Calendar")
(my/cheatsheet-add "Casual Menus" 'casual-eww-tmenu "Transient menu for EWW browser")

;;;; ---- Help & Discovery ----

(my/cheatsheet-add "Help & Discovery" 'embark-bindings "Explore all key bindings via completion")
(my/cheatsheet-add "Help & Discovery" 'embark-prefix-help-command "Show commands under prefix key")
(my/cheatsheet-add "Help & Discovery" 'consult-info "Full text search through Info manuals")
(my/cheatsheet-add "Help & Discovery" 'consult-man "Search and open man pages")
(my/cheatsheet-add "Help & Discovery" 'consult-theme "Switch color theme with live preview")
(my/cheatsheet-add "Help & Discovery" 'consult-minor-mode-menu "Toggle minor mode via completion")
(my/cheatsheet-add "Help & Discovery" 'consult-mode-command "Run command from active modes")
(my/cheatsheet-add "Help & Discovery" 'consult-kmacro "Select and run a keyboard macro")
(my/cheatsheet-add "Help & Discovery" 'consult-register "Browse and use registers with preview")
(my/cheatsheet-add "Help & Discovery" 'consult-register-store "Store to register with action menu")
(my/cheatsheet-add "Help & Discovery" 'consult-complex-command "Re-evaluate a past command")
(my/cheatsheet-add "Help & Discovery" 'consult-compile-error "Jump to compilation error with preview")
(my/cheatsheet-add "Help & Discovery" 'my/cheatsheet "Open this cheatsheet")

;;; =========================================================================
;;; Built-in Emacs keybindings (extracted from Emacs source)
;;; =========================================================================

;;;; ---- Emacs: Movement ----

(my/cheatsheet-add "Emacs: Movement" 'forward-char "Move forward one character")
(my/cheatsheet-add "Emacs: Movement" 'backward-char "Move backward one character")
(my/cheatsheet-add "Emacs: Movement" 'forward-word "Move forward one word")
(my/cheatsheet-add "Emacs: Movement" 'backward-word "Move backward one word")
(my/cheatsheet-add "Emacs: Movement" 'next-line "Move down one line")
(my/cheatsheet-add "Emacs: Movement" 'previous-line "Move up one line")
(my/cheatsheet-add "Emacs: Movement" 'move-beginning-of-line "Move to beginning of line")
(my/cheatsheet-add "Emacs: Movement" 'move-end-of-line "Move to end of line")
(my/cheatsheet-add "Emacs: Movement" 'back-to-indentation "Move to first non-whitespace on line")
(my/cheatsheet-add "Emacs: Movement" 'forward-sentence "Move forward to end of sentence")
(my/cheatsheet-add "Emacs: Movement" 'backward-sentence "Move backward to start of sentence")
(my/cheatsheet-add "Emacs: Movement" 'forward-paragraph "Move forward to end of paragraph")
(my/cheatsheet-add "Emacs: Movement" 'backward-paragraph "Move backward to start of paragraph")
(my/cheatsheet-add "Emacs: Movement" 'forward-page "Move forward one page")
(my/cheatsheet-add "Emacs: Movement" 'backward-page "Move backward one page")
(my/cheatsheet-add "Emacs: Movement" 'beginning-of-buffer "Move to beginning of buffer")
(my/cheatsheet-add "Emacs: Movement" 'end-of-buffer "Move to end of buffer")
(my/cheatsheet-add "Emacs: Movement" 'goto-line "Go to a line number")
(my/cheatsheet-add "Emacs: Movement" 'goto-char "Go to a character position")
(my/cheatsheet-add "Emacs: Movement" 'move-to-column "Move to a specific column")
(my/cheatsheet-add "Emacs: Movement" 'move-to-window-line-top-bottom "Cycle point between center/top/bottom")
(my/cheatsheet-add "Emacs: Movement" 'recenter-top-bottom "Cycle recenter: center, top, bottom")
(my/cheatsheet-add "Emacs: Movement" 'set-goal-column "Set/unset goal column for C-n/C-p")
(my/cheatsheet-add "Emacs: Movement" 'scroll-up-command "Scroll forward one screenful")
(my/cheatsheet-add "Emacs: Movement" 'scroll-down-command "Scroll backward one screenful")
(my/cheatsheet-add "Emacs: Movement" 'scroll-other-window "Scroll other window forward")
(my/cheatsheet-add "Emacs: Movement" 'scroll-other-window-down "Scroll other window backward")
(my/cheatsheet-add "Emacs: Movement" 'scroll-left "Scroll window left")
(my/cheatsheet-add "Emacs: Movement" 'scroll-right "Scroll window right")

;;;; ---- Emacs: Sexp & Defun ----

(my/cheatsheet-add "Emacs: Sexp & Defun" 'forward-sexp "Move forward over balanced expression")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'backward-sexp "Move backward over balanced expression")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'forward-list "Move forward over parenthesized group")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'backward-list "Move backward over parenthesized group")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'down-list "Move down into nested parentheses")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'backward-up-list "Move up out of enclosing parentheses")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'mark-sexp "Set mark after next sexp")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'kill-sexp "Kill the sexp after point")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'backward-kill-sexp "Kill the sexp before point")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'transpose-sexps "Transpose sexps around point")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'beginning-of-defun "Move to beginning of current defun")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'end-of-defun "Move to end of current defun")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'mark-defun "Mark entire current defun")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'narrow-to-defun "Narrow buffer to current defun")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'insert-parentheses "Insert balanced parentheses")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'move-past-close-and-reindent "Move past close-paren and reindent")
(my/cheatsheet-add "Emacs: Sexp & Defun" 'prog-indent-sexp "Indent the sexp after point")

;;;; ---- Emacs: Kill & Yank ----

(my/cheatsheet-add "Emacs: Kill & Yank" 'kill-line "Kill from point to end of line")
(my/cheatsheet-add "Emacs: Kill & Yank" 'kill-whole-line "Kill entire line including newline")
(my/cheatsheet-add "Emacs: Kill & Yank" 'kill-region "Kill (cut) the region")
(my/cheatsheet-add "Emacs: Kill & Yank" 'kill-ring-save "Copy the region to kill ring")
(my/cheatsheet-add "Emacs: Kill & Yank" 'yank "Yank (paste) most recent kill")
(my/cheatsheet-add "Emacs: Kill & Yank" 'yank-pop "Cycle through kill ring after yank")
(my/cheatsheet-add "Emacs: Kill & Yank" 'append-next-kill "Append next kill to previous entry")
(my/cheatsheet-add "Emacs: Kill & Yank" 'kill-word "Kill forward to end of word")
(my/cheatsheet-add "Emacs: Kill & Yank" 'backward-kill-word "Kill backward to start of word")
(my/cheatsheet-add "Emacs: Kill & Yank" 'kill-sentence "Kill forward to end of sentence")
(my/cheatsheet-add "Emacs: Kill & Yank" 'backward-kill-sentence "Kill backward to start of sentence")
(my/cheatsheet-add "Emacs: Kill & Yank" 'zap-to-char "Kill through a specified character")

;;;; ---- Emacs: Mark & Region ----

(my/cheatsheet-add "Emacs: Mark & Region" 'set-mark-command "Set mark at point / activate region")
(my/cheatsheet-add "Emacs: Mark & Region" 'exchange-point-and-mark "Exchange point and mark")
(my/cheatsheet-add "Emacs: Mark & Region" 'pop-global-mark "Jump to previous global mark")
(my/cheatsheet-add "Emacs: Mark & Region" 'rectangle-mark-mode "Toggle rectangular region marking")
(my/cheatsheet-add "Emacs: Mark & Region" 'mark-word "Set mark after next word")
(my/cheatsheet-add "Emacs: Mark & Region" 'mark-paragraph "Mark current paragraph")
(my/cheatsheet-add "Emacs: Mark & Region" 'mark-page "Mark current page")
(my/cheatsheet-add "Emacs: Mark & Region" 'mark-whole-buffer "Select entire buffer")
(my/cheatsheet-add "Emacs: Mark & Region" 'narrow-to-region "Narrow buffer to selected region")
(my/cheatsheet-add "Emacs: Mark & Region" 'widen "Remove narrowing, show full buffer")

;;;; ---- Emacs: Text Editing ----

(my/cheatsheet-add "Emacs: Text Editing" 'delete-char "Delete character after point")
(my/cheatsheet-add "Emacs: Text Editing" 'delete-backward-char "Delete character before point")
(my/cheatsheet-add "Emacs: Text Editing" 'delete-horizontal-space "Delete all spaces/tabs around point")
(my/cheatsheet-add "Emacs: Text Editing" 'cycle-spacing "Cycle spacing: one space, none, restore")
(my/cheatsheet-add "Emacs: Text Editing" 'delete-blank-lines "Delete blank lines around point")
(my/cheatsheet-add "Emacs: Text Editing" 'delete-indentation "Join line to previous, remove indent")
(my/cheatsheet-add "Emacs: Text Editing" 'transpose-chars "Transpose characters around point")
(my/cheatsheet-add "Emacs: Text Editing" 'transpose-words "Transpose words around point")
(my/cheatsheet-add "Emacs: Text Editing" 'transpose-lines "Transpose current and previous line")
(my/cheatsheet-add "Emacs: Text Editing" 'upcase-word "Uppercase the following word")
(my/cheatsheet-add "Emacs: Text Editing" 'downcase-word "Lowercase the following word")
(my/cheatsheet-add "Emacs: Text Editing" 'capitalize-word "Capitalize the following word")
(my/cheatsheet-add "Emacs: Text Editing" 'upcase-region "Uppercase the region")
(my/cheatsheet-add "Emacs: Text Editing" 'downcase-region "Lowercase the region")
(my/cheatsheet-add "Emacs: Text Editing" 'indent-for-tab-command "Indent line or region per mode")
(my/cheatsheet-add "Emacs: Text Editing" 'indent-rigidly "Indent region by fixed amount")
(my/cheatsheet-add "Emacs: Text Editing" 'indent-region "Indent each line in region per mode")
(my/cheatsheet-add "Emacs: Text Editing" 'newline "Insert a newline")
(my/cheatsheet-add "Emacs: Text Editing" 'open-line "Insert newline after point")
(my/cheatsheet-add "Emacs: Text Editing" 'split-line "Split line at point, indent to column")
(my/cheatsheet-add "Emacs: Text Editing" 'quoted-insert "Insert next character literally")
(my/cheatsheet-add "Emacs: Text Editing" 'comment-dwim "Comment/uncomment (Do What I Mean)")
(my/cheatsheet-add "Emacs: Text Editing" 'comment-line "Comment or uncomment current line(s)")
(my/cheatsheet-add "Emacs: Text Editing" 'fill-paragraph "Fill (word-wrap) current paragraph")
(my/cheatsheet-add "Emacs: Text Editing" 'set-fill-column "Set fill column")
(my/cheatsheet-add "Emacs: Text Editing" 'count-words-region "Count words in region")
(my/cheatsheet-add "Emacs: Text Editing" 'what-cursor-position "Display info about char at point")

;;;; ---- Emacs: Undo & Repeat ----

(my/cheatsheet-add "Emacs: Undo & Repeat" 'undo "Undo last change")
(my/cheatsheet-add "Emacs: Undo & Repeat" 'undo-redo "Redo (undo the last undo)")
(my/cheatsheet-add "Emacs: Undo & Repeat" 'repeat "Repeat most recent command")
(my/cheatsheet-add "Emacs: Undo & Repeat" 'repeat-complex-command "Edit and re-evaluate last complex command")
(my/cheatsheet-add "Emacs: Undo & Repeat" 'keyboard-quit "Quit current operation")
(my/cheatsheet-add "Emacs: Undo & Repeat" 'keyboard-escape-quit "Universal quit: exit anything")

;;;; ---- Emacs: Search & Replace ----

(my/cheatsheet-add "Emacs: Search & Replace" 'isearch-forward "Incremental search forward")
(my/cheatsheet-add "Emacs: Search & Replace" 'isearch-backward "Incremental search backward")
(my/cheatsheet-add "Emacs: Search & Replace" 'isearch-forward-regexp "Regexp incremental search forward")
(my/cheatsheet-add "Emacs: Search & Replace" 'isearch-backward-regexp "Regexp incremental search backward")
(my/cheatsheet-add "Emacs: Search & Replace" 'isearch-forward-word "Incremental word search forward")
(my/cheatsheet-add "Emacs: Search & Replace" 'isearch-forward-symbol "Incremental symbol search forward")
(my/cheatsheet-add "Emacs: Search & Replace" 'isearch-forward-symbol-at-point "Search forward for symbol at point")
(my/cheatsheet-add "Emacs: Search & Replace" 'isearch-forward-thing-at-point "Search forward for thing at point")
(my/cheatsheet-add "Emacs: Search & Replace" 'query-replace "Interactively replace string matches")
(my/cheatsheet-add "Emacs: Search & Replace" 'query-replace-regexp "Interactively replace regexp matches")
(my/cheatsheet-add "Emacs: Search & Replace" 'occur "List all lines matching a regexp")
(my/cheatsheet-add "Emacs: Search & Replace" 'highlight-regexp "Highlight text matching a regexp")
(my/cheatsheet-add "Emacs: Search & Replace" 'highlight-phrase "Highlight text matching a phrase")
(my/cheatsheet-add "Emacs: Search & Replace" 'highlight-symbol-at-point "Highlight symbol at point")
(my/cheatsheet-add "Emacs: Search & Replace" 'unhighlight-regexp "Remove regexp highlighting")

;;;; ---- Emacs: Isearch Keys ----

(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-repeat-forward "Next match in current direction")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-repeat-backward "Previous match in current direction")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-exit "Exit isearch, leave point at match")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-abort "Abort isearch, return to start")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-delete-char "Undo last isearch input item")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-edit-string "Edit search string in minibuffer")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-yank-word-or-char "Yank word at cursor into search")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-yank-symbol-or-char "Yank symbol at cursor into search")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-yank-kill "Yank kill ring into search string")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-yank-line "Yank rest of line into search string")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-yank-char "Yank next character into search")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-ring-advance "Next item in search history")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-ring-retreat "Previous item in search history")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-toggle-case-fold "Toggle case-sensitive searching")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-toggle-regexp "Toggle regexp search mode")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-toggle-word "Toggle word search mode")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-toggle-symbol "Toggle symbol search mode")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-toggle-lax-whitespace "Toggle lax whitespace matching")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-toggle-invisible "Toggle searching invisible text")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-query-replace "Switch to query-replace from isearch")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-query-replace-regexp "Switch to regexp query-replace")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-occur "Run occur with search string")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-highlight-regexp "Highlight all search matches")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-beginning-of-buffer "Jump to first match in buffer")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-end-of-buffer "Jump to last match in buffer")
(my/cheatsheet-add "Emacs: Isearch Keys" 'isearch-complete "Complete search string from history")

;;;; ---- Emacs: Windows ----

(my/cheatsheet-add "Emacs: Windows" 'split-window-below "Split window vertically (top/bottom)")
(my/cheatsheet-add "Emacs: Windows" 'split-window-right "Split window horizontally (left/right)")
(my/cheatsheet-add "Emacs: Windows" 'delete-window "Delete the selected window")
(my/cheatsheet-add "Emacs: Windows" 'delete-other-windows "Delete all windows except selected")
(my/cheatsheet-add "Emacs: Windows" 'other-window "Select next window in cyclic order")
(my/cheatsheet-add "Emacs: Windows" 'other-window-backward "Select previous window in cyclic order")
(my/cheatsheet-add "Emacs: Windows" 'enlarge-window "Make window one line taller")
(my/cheatsheet-add "Emacs: Windows" 'enlarge-window-horizontally "Make window one column wider")
(my/cheatsheet-add "Emacs: Windows" 'shrink-window-horizontally "Make window one column narrower")
(my/cheatsheet-add "Emacs: Windows" 'shrink-window-if-larger-than-buffer "Shrink window to fit content")
(my/cheatsheet-add "Emacs: Windows" 'balance-windows "Make all windows the same size")
(my/cheatsheet-add "Emacs: Windows" 'fit-window-to-buffer "Fit window height to buffer content")
(my/cheatsheet-add "Emacs: Windows" 'kill-buffer-and-window "Kill buffer and delete its window")
(my/cheatsheet-add "Emacs: Windows" 'split-root-window-below "Split root window vertically")
(my/cheatsheet-add "Emacs: Windows" 'split-root-window-right "Split root window horizontally")
(my/cheatsheet-add "Emacs: Windows" 'window-layout-transpose "Transpose the window layout")
(my/cheatsheet-add "Emacs: Windows" 'rotate-windows "Rotate windows forward")
(my/cheatsheet-add "Emacs: Windows" 'rotate-windows-back "Rotate windows backward")
(my/cheatsheet-add "Emacs: Windows" 'window-toggle-side-windows "Toggle side windows on/off")
(my/cheatsheet-add "Emacs: Windows" 'toggle-window-dedicated "Toggle window dedicated to buffer")
(my/cheatsheet-add "Emacs: Windows" 'quit-window "Quit window (bury or kill buffer)")
(my/cheatsheet-add "Emacs: Windows" 'other-window-prefix "Next command's buffer in other window")
(my/cheatsheet-add "Emacs: Windows" 'same-window-prefix "Next command's buffer in same window")

;;;; ---- Emacs: Frames ----

(my/cheatsheet-add "Emacs: Frames" 'make-frame-command "Create a new frame")
(my/cheatsheet-add "Emacs: Frames" 'delete-frame "Delete the selected frame")
(my/cheatsheet-add "Emacs: Frames" 'delete-other-frames "Delete all frames except selected")
(my/cheatsheet-add "Emacs: Frames" 'other-frame "Select the next frame")
(my/cheatsheet-add "Emacs: Frames" 'clone-frame "Clone the current frame")
(my/cheatsheet-add "Emacs: Frames" 'undelete-frame "Undelete most recently deleted frame")
(my/cheatsheet-add "Emacs: Frames" 'toggle-frame-fullscreen "Toggle fullscreen mode")
(my/cheatsheet-add "Emacs: Frames" 'toggle-frame-maximized "Toggle maximized state")
(my/cheatsheet-add "Emacs: Frames" 'other-frame-prefix "Next command's buffer in other frame")
(my/cheatsheet-add "Emacs: Frames" 'tear-off-window "Tear off window into a new frame")

;;;; ---- Emacs: Tabs ----

(my/cheatsheet-add "Emacs: Tabs" 'tab-new "Create a new tab")
(my/cheatsheet-add "Emacs: Tabs" 'tab-close "Close the current tab")
(my/cheatsheet-add "Emacs: Tabs" 'tab-close-other "Close all other tabs")
(my/cheatsheet-add "Emacs: Tabs" 'tab-next "Switch to the next tab")
(my/cheatsheet-add "Emacs: Tabs" 'tab-previous "Switch to the previous tab")
(my/cheatsheet-add "Emacs: Tabs" 'tab-undo "Undo the last tab close")
(my/cheatsheet-add "Emacs: Tabs" 'tab-duplicate "Duplicate the current tab")
(my/cheatsheet-add "Emacs: Tabs" 'tab-move "Move the current tab forward")
(my/cheatsheet-add "Emacs: Tabs" 'tab-rename "Rename the current tab")
(my/cheatsheet-add "Emacs: Tabs" 'tab-switch "Switch to a tab by name")
(my/cheatsheet-add "Emacs: Tabs" 'tab-group "Change the tab group")
(my/cheatsheet-add "Emacs: Tabs" 'tab-detach "Detach tab into a new frame")
(my/cheatsheet-add "Emacs: Tabs" 'tab-window-detach "Detach window into a new tab")
(my/cheatsheet-add "Emacs: Tabs" 'tab-recent "Select most recently visited tab")
(my/cheatsheet-add "Emacs: Tabs" 'find-file-other-tab "Find file in another tab")
(my/cheatsheet-add "Emacs: Tabs" 'switch-to-buffer-other-tab "Switch buffer in another tab")

;;;; ---- Emacs: Files ----

(my/cheatsheet-add "Emacs: Files" 'find-file "Open (visit) a file")
(my/cheatsheet-add "Emacs: Files" 'find-file-other-window "Open file in another window")
(my/cheatsheet-add "Emacs: Files" 'find-file-read-only "Open file in read-only mode")
(my/cheatsheet-add "Emacs: Files" 'find-alternate-file "Replace buffer with another file")
(my/cheatsheet-add "Emacs: Files" 'save-buffer "Save current buffer to file")
(my/cheatsheet-add "Emacs: Files" 'save-some-buffers "Offer to save modified buffers")
(my/cheatsheet-add "Emacs: Files" 'write-file "Write buffer to a different file")
(my/cheatsheet-add "Emacs: Files" 'insert-file "Insert file contents at point")
(my/cheatsheet-add "Emacs: Files" 'revert-buffer-quick "Revert buffer without confirmation")
(my/cheatsheet-add "Emacs: Files" 'read-only-mode "Toggle read-only mode")
(my/cheatsheet-add "Emacs: Files" 'dired-jump "Jump to current file in dired")
(my/cheatsheet-add "Emacs: Files" 'save-buffers-kill-terminal "Save buffers and exit Emacs")

;;;; ---- Emacs: Buffers ----

(my/cheatsheet-add "Emacs: Buffers" 'switch-to-buffer "Switch to a named buffer")
(my/cheatsheet-add "Emacs: Buffers" 'switch-to-buffer-other-window "Switch buffer in other window")
(my/cheatsheet-add "Emacs: Buffers" 'kill-buffer "Kill a buffer")
(my/cheatsheet-add "Emacs: Buffers" 'list-buffers "Display list of all buffers")
(my/cheatsheet-add "Emacs: Buffers" 'next-buffer "Switch to the next buffer")
(my/cheatsheet-add "Emacs: Buffers" 'previous-buffer "Switch to the previous buffer")
(my/cheatsheet-add "Emacs: Buffers" 'rename-buffer "Rename the current buffer")
(my/cheatsheet-add "Emacs: Buffers" 'clone-buffer "Clone the current buffer")
(my/cheatsheet-add "Emacs: Buffers" 'clone-indirect-buffer-other-window "Clone indirect buffer in other window")
(my/cheatsheet-add "Emacs: Buffers" 'not-modified "Clear the modified flag on buffer")
(my/cheatsheet-add "Emacs: Buffers" 'display-buffer "Display buffer without selecting")

;;;; ---- Emacs: Help ----

(my/cheatsheet-add "Emacs: Help" 'describe-function "Describe a function")
(my/cheatsheet-add "Emacs: Help" 'describe-variable "Describe a variable")
(my/cheatsheet-add "Emacs: Help" 'describe-key "Describe what a key does")
(my/cheatsheet-add "Emacs: Help" 'describe-key-briefly "Show command name for a key")
(my/cheatsheet-add "Emacs: Help" 'describe-symbol "Describe any symbol")
(my/cheatsheet-add "Emacs: Help" 'describe-command "Describe a command")
(my/cheatsheet-add "Emacs: Help" 'describe-mode "Describe current major/minor modes")
(my/cheatsheet-add "Emacs: Help" 'describe-bindings "Show all current key bindings")
(my/cheatsheet-add "Emacs: Help" 'describe-package "Describe an Emacs package")
(my/cheatsheet-add "Emacs: Help" 'apropos-command "Search commands by name/regexp")
(my/cheatsheet-add "Emacs: Help" 'apropos-documentation "Search documentation by keyword")
(my/cheatsheet-add "Emacs: Help" 'apropos-user-option "Search user options by regexp")
(my/cheatsheet-add "Emacs: Help" 'where-is "Show keys bound to a command")
(my/cheatsheet-add "Emacs: Help" 'info "Open Info documentation browser")
(my/cheatsheet-add "Emacs: Help" 'info-emacs-manual "Open the Emacs manual")
(my/cheatsheet-add "Emacs: Help" 'info-display-manual "Open a specific Info manual")
(my/cheatsheet-add "Emacs: Help" 'info-lookup-symbol "Look up symbol in reference manual")
(my/cheatsheet-add "Emacs: Help" 'Info-goto-emacs-command-node "Look up command in Emacs manual")
(my/cheatsheet-add "Emacs: Help" 'view-lossage "Show last 300 keystrokes")
(my/cheatsheet-add "Emacs: Help" 'view-echo-area-messages "Show *Messages* buffer")
(my/cheatsheet-add "Emacs: Help" 'help-with-tutorial "Open the Emacs tutorial")
(my/cheatsheet-add "Emacs: Help" 'help-quick-toggle "Toggle quick help reference")

;;;; ---- Emacs: Registers ----

(my/cheatsheet-add "Emacs: Registers" 'point-to-register "Store point position in register")
(my/cheatsheet-add "Emacs: Registers" 'jump-to-register "Jump to position in register")
(my/cheatsheet-add "Emacs: Registers" 'copy-to-register "Copy region to a register")
(my/cheatsheet-add "Emacs: Registers" 'insert-register "Insert register contents at point")
(my/cheatsheet-add "Emacs: Registers" 'number-to-register "Store a number in a register")
(my/cheatsheet-add "Emacs: Registers" 'increment-register "Increment number in a register")
(my/cheatsheet-add "Emacs: Registers" 'window-configuration-to-register "Store window config in register")
(my/cheatsheet-add "Emacs: Registers" 'frameset-to-register "Store all frame configs in register")
(my/cheatsheet-add "Emacs: Registers" 'copy-rectangle-to-register "Copy rectangle to a register")

;;;; ---- Emacs: Bookmarks ----

(my/cheatsheet-add "Emacs: Bookmarks" 'bookmark-set "Set a bookmark at point")
(my/cheatsheet-add "Emacs: Bookmarks" 'bookmark-set-no-overwrite "Set bookmark (error if exists)")
(my/cheatsheet-add "Emacs: Bookmarks" 'bookmark-jump "Jump to a bookmark")
(my/cheatsheet-add "Emacs: Bookmarks" 'bookmark-bmenu-list "Display the bookmark list")
(my/cheatsheet-add "Emacs: Bookmarks" 'bookmark-rename "Rename a bookmark")
(my/cheatsheet-add "Emacs: Bookmarks" 'bookmark-delete "Delete a bookmark")
(my/cheatsheet-add "Emacs: Bookmarks" 'bookmark-save "Save bookmarks to default file")

;;;; ---- Emacs: Keyboard Macros ----

(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-start-macro-or-insert-counter "Start macro or insert counter")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-end-or-call-macro "End macro definition or call last")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-start-macro "Start defining a keyboard macro")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-end-macro "End defining a keyboard macro")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-end-and-call-macro "End macro and call it")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'apply-macro-to-region-lines "Apply macro to each line in region")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kbd-macro-query "Query user during macro execution")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-cycle-ring-next "Cycle to next macro in ring")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-cycle-ring-previous "Cycle to previous macro in ring")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-edit-macro "Edit last keyboard macro")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-step-edit-macro "Step-edit last macro")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-bind-to-key "Bind last macro to a key")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-name-last-macro "Give last macro a name")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-to-register "Store last macro in a register")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-set-counter "Set macro counter value")
(my/cheatsheet-add "Emacs: Keyboard Macros" 'kmacro-insert-counter "Insert macro counter at point")

;;;; ---- Emacs: Rectangles ----

(my/cheatsheet-add "Emacs: Rectangles" 'kill-rectangle "Kill rectangle region")
(my/cheatsheet-add "Emacs: Rectangles" 'copy-rectangle-as-kill "Copy rectangle without deleting")
(my/cheatsheet-add "Emacs: Rectangles" 'delete-rectangle "Delete rectangle (don't save)")
(my/cheatsheet-add "Emacs: Rectangles" 'yank-rectangle "Yank last killed rectangle")
(my/cheatsheet-add "Emacs: Rectangles" 'open-rectangle "Blank out rectangle, shift text right")
(my/cheatsheet-add "Emacs: Rectangles" 'clear-rectangle "Blank out rectangle with spaces")
(my/cheatsheet-add "Emacs: Rectangles" 'string-rectangle "Replace rectangle with a string")
(my/cheatsheet-add "Emacs: Rectangles" 'rectangle-number-lines "Insert line numbers in rectangle")

;;;; ---- Emacs: Abbreviations ----

(my/cheatsheet-add "Emacs: Abbreviations" 'add-global-abbrev "Add a global abbreviation")
(my/cheatsheet-add "Emacs: Abbreviations" 'add-mode-abbrev "Add a mode-specific abbreviation")
(my/cheatsheet-add "Emacs: Abbreviations" 'inverse-add-global-abbrev "Define abbrev from word before point")
(my/cheatsheet-add "Emacs: Abbreviations" 'expand-abbrev "Expand the abbreviation before point")

;;;; ---- Emacs: Shell & Eval ----

(my/cheatsheet-add "Emacs: Shell & Eval" 'shell-command "Run a shell command")
(my/cheatsheet-add "Emacs: Shell & Eval" 'shell-command-on-region "Run shell command on region")
(my/cheatsheet-add "Emacs: Shell & Eval" 'async-shell-command "Run async shell command")
(my/cheatsheet-add "Emacs: Shell & Eval" 'eval-expression "Evaluate Emacs Lisp expression")
(my/cheatsheet-add "Emacs: Shell & Eval" 'eval-last-sexp "Evaluate sexp before point")
(my/cheatsheet-add "Emacs: Shell & Eval" 'execute-extended-command "Run command by name (M-x)")

;;;; ---- Emacs: Prefix Arguments ----

(my/cheatsheet-add "Emacs: Prefix Arguments" 'universal-argument "Begin universal numeric argument")
(my/cheatsheet-add "Emacs: Prefix Arguments" 'digit-argument "Numeric prefix digit")
(my/cheatsheet-add "Emacs: Prefix Arguments" 'negative-argument "Negative prefix argument")

;;;; ---- Emacs: Error Navigation ----

(my/cheatsheet-add "Emacs: Error Navigation" 'next-error "Visit next error/match")
(my/cheatsheet-add "Emacs: Error Navigation" 'previous-error "Visit previous error/match")
(my/cheatsheet-add "Emacs: Error Navigation" 'next-error-follow-minor-mode "Toggle follow mode for errors")

;;;; ---- Emacs: Xref ----

(my/cheatsheet-add "Emacs: Xref" 'xref-find-definitions "Find definition at point")
(my/cheatsheet-add "Emacs: Xref" 'xref-go-back "Go back in xref history")
(my/cheatsheet-add "Emacs: Xref" 'xref-go-forward "Go forward in xref history")
(my/cheatsheet-add "Emacs: Xref" 'xref-find-references "Find all references at point")
(my/cheatsheet-add "Emacs: Xref" 'xref-find-apropos "Find symbols matching a pattern")
(my/cheatsheet-add "Emacs: Xref" 'xref-find-definitions-other-window "Find definition in other window")
(my/cheatsheet-add "Emacs: Xref" 'xref-find-definitions-other-frame "Find definition in other frame")
(my/cheatsheet-add "Emacs: Xref" 'xref-query-replace-in-results "Query-replace across xref results")

;;;; ---- Emacs: Compilation ----

(my/cheatsheet-add "Emacs: Compilation" 'compile "Run compile command")
(my/cheatsheet-add "Emacs: Compilation" 'recompile "Re-run last compilation")
(my/cheatsheet-add "Emacs: Compilation" 'compile-goto-error "Visit source for error at point")
(my/cheatsheet-add "Emacs: Compilation" 'kill-compilation "Kill running compilation process")
(my/cheatsheet-add "Emacs: Compilation" 'compilation-next-error "Move to next error in compilation")
(my/cheatsheet-add "Emacs: Compilation" 'compilation-previous-error "Move to previous error in compilation")

;;;; ---- Emacs: Other Window/Frame Prefix ----

(my/cheatsheet-add "Emacs: C-x 4 / C-x 5" 'find-file-other-window "Open file in other window")
(my/cheatsheet-add "Emacs: C-x 4 / C-x 5" 'switch-to-buffer-other-window "Switch buffer in other window")
(my/cheatsheet-add "Emacs: C-x 4 / C-x 5" 'dired-other-window "Open dired in other window")
(my/cheatsheet-add "Emacs: C-x 4 / C-x 5" 'find-file-other-frame "Open file in other frame")
(my/cheatsheet-add "Emacs: C-x 4 / C-x 5" 'switch-to-buffer-other-frame "Switch buffer in other frame")
(my/cheatsheet-add "Emacs: C-x 4 / C-x 5" 'display-buffer "Display buffer in some window")
(my/cheatsheet-add "Emacs: C-x 4 / C-x 5" 'display-buffer-other-frame "Display buffer in other frame")

;;; cheatsheet-entries.el ends here
